---
# 
# Reboot cluster nodes (if necessary)
#
- name: Check reboot needed
  command: /sbin/reboot removes=/var/run/reboot-required
  register: host_rebooted

- name: Wait for the server to reboot
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=20 timeout=120 state=started
  sudo: False
  when: host_rebooted.changed
