---
# 
# AWS vars (ami-823686f5 = Ubuntu 14.04 LTS, hvm:ebs-ssd)
#
aws_image: ami-823686f5
aws_region: eu-west-1
aws_zone1: eu-west-1a
aws_zone2: eu-west-1b
aws_zone3: eu-west-1c

cluster_node_volumes:
  - device_name: /dev/sda1
    volume_size: "{{ cluster_node_disk_size }}"
    device_type: gp2
    delete_on_termination: true
